
services:
  mongo:
    image: mongo
    container_name: jamoveo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: jamoveo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    container_name: jamoveo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  mongo-data: