
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    command: >
      bash -c "
        mongod --bind_ip_all & 
        sleep 5 && 
        mongoimport --host localhost --db jamoveo --collection songs --file ./backend/songs.json --jsonArray &&
        fg"

  backend:
    build: ./backend
    container_name: jamoveo-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: jamoveo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  mongo-data: